### ISSUE TITLE
Option flow config_entry explicitly is deprecated

### ISSUE THREAD

**Issue by marcinn2** [kubawolanin/ha-openhab#32]
Detected that custom integration 'openhab' sets option flow config_entry explicitly, which is deprecated at custom_components/openhab/config_flow.py, line 146: self.config_entry = config_entry.

## Version of the custom_component

-     Home Assistant version: 2025.11.3
-     Integration version: Latest from main branch
-     openHAB version: 3.2.0

## Configuration

standard configuration

## Error Message

```
2025-12-10 10:33:04.114 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'openhab' sets option flow config_entry explicitly, which is deprecated at custom_components/openhab/config_flow.py, line 146: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/kubawolanin/ha-openhab/issues
2025-12-10 10:33:16.056 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry x.x.x.x for openhab
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/openhab/__init__.py", line 51, in async_setup_entry
hass.config_entries.async_forward_entry_setup(entry, platform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-12-10 10:38:29.641 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry x.x.x.x for openhab
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/openhab/__init__.py", line 51, in async_setup_entry
hass.config_entries.async_forward_entry_setup(entry, platform)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

## Describe the bug
After upgrade to HomeAssistant 2025.11  integration does not start with error in logs.

## Solution
Replace attached files ( generated automatically by AI)

[__init__.py](https://github.com/user-attachments/files/24075161/__init__.py)
[config_flow.py](https://github.com/user-attachments/files/24075160/config_flow.py)
